import type { EndpointSpec, ParamSpec } from "./types";

const ranchQ: ParamSpec = { name: "ranch_id", in: "query", type: "string", description: "Only this ranch." };
const E404 = { status: 404, when: "Unknown id." };
const ANIMAL_NOT_FOUND = { status: 404, when: "Unknown animal.", code: "animal.not_found" };

/**
 * Every endpoint the frontend calls (or will call), including the ones the animal-service swagger
 * already has. Whether each is New / Changed / Exists is worked out by comparing with that swagger.
 * `fn` is the function in src/lib/api.ts that these replace.
 */
export const ENDPOINTS: EndpointSpec[] = [
  // ======================= animal-service =======================
  {
    method: "POST",
    path: "/animals",
    service: "animal",
    summary: "Register an animal",
    priority: "required",
    ui: ["New animal"],
    body: "AnimalCreate",
    responses: [{ status: 201, schema: "AnimalOut" }],
    rules: ["Writes an animal_created audit event in the same transaction."],
    errors: [{ status: 409, when: "tag_id already exists.", code: "animal.duplicate_tag" }],
  },
  {
    method: "GET",
    path: "/animals",
    service: "animal",
    summary: "List animals",
    priority: "required",
    ui: ["Animals list", "Pickers in forms", "Tag lookups for audit events, maps and movements"],
    fn: "listAnimals, getAnimalTags",
    params: [
      { name: "ranch_id", in: "query", type: "string", description: "Only this ranch." },
      { name: "status_filter", in: "query", type: "string", description: "active, sold or deceased." },
      { name: "ids", in: "query", type: "string", description: "Comma-separated ids, to look up tags and nicknames for a few animals. Recommended once herds get large." },
      { name: "q", in: "query", type: "string", description: "Search tag, nickname and registry number. The UI filters client-side today; recommended once the list is paginated." },
      { name: "limit", in: "query", type: "integer", description: "Page size. The UI assumes the full list today." },
      { name: "offset", in: "query", type: "integer" },
    ],
    responses: [{ status: 200, schema: "AnimalOut", array: true }],
    rules: ["The UI currently loads every animal once (also to turn ids into tags and nicknames), so an unpaginated list must stay available until `ids` and `q` exist."],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}",
    service: "animal",
    summary: "Get an animal",
    priority: "required",
    ui: ["Animal page", "Edit animal", "Print records", "QR tag"],
    fn: "getAnimal",
    responses: [{ status: 200, schema: "AnimalOut" }],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "PATCH",
    path: "/animals/{animal_id}",
    service: "animal",
    summary: "Update an animal (edit, mark sold, update lineage)",
    priority: "required",
    ui: ["Edit animal", "Print records (“Mark as sold” and undo)", "Record menu → Update lineage"],
    fn: "setAnimalStatus, updateLineage",
    body: "AnimalUpdate",
    responses: [{ status: 200, schema: "AnimalOut" }],
    rules: [
      "Status changes the UI performs: active → sold, and sold → active (undo). Each writes an animal_updated audit event with { status }.",
      "Changing sire_id or dam_id writes a lineage_updated audit event with { sire, dam } (tag ids, or null).",
      "sire_id must belong to a bull and dam_id to a cow or heifer.",
      "An animal can't be its own ancestor: reject a sire or dam that is the animal itself or one of its descendants (walk the tree, any depth).",
      "Setting status to sold or deceased removes the animal from live maps, boundary alerts and head counts. History stays queryable.",
    ],
    errors: [
      ANIMAL_NOT_FOUND,
      { status: 422, when: "sire_id is not a bull.", code: "lineage.sire_not_bull" },
      { status: 422, when: "dam_id is not a cow or heifer.", code: "lineage.dam_not_female" },
      { status: 422, when: "sire or dam is the animal itself or its descendant.", code: "lineage.cycle" },
      { status: 409, when: "Selling an animal that isn't active.", code: "status.not_active" },
      { status: 409, when: "Undoing a sale on an animal that isn't sold.", code: "status.not_sold" },
    ],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/lineage",
    service: "animal",
    summary: "Family tree",
    priority: "required",
    ui: ["Animal page (Lineage card)", "Print records"],
    fn: "getLineage",
    params: [{ name: "depth", in: "query", type: "integer", description: "Generations above the animal. Default 3." }],
    responses: [{ status: 200, schema: "LineageNode" }],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/audit-trail",
    service: "animal",
    summary: "Audit trail for one animal",
    priority: "required",
    ui: ["Animal page (Audit trail)"],
    fn: "getAnimalAuditTrail",
    responses: [{ status: 200, schema: "AuditEventOut", array: true }],
    rules: ["Newest first. Event types and their event_data are in the “Audit event catalog” below. Events from every service appear in one list."],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "POST",
    path: "/animals/{animal_id}/identifiers",
    service: "animal",
    summary: "Attach an identifier (RFID, EID, tattoo, muzzle print)",
    priority: "required",
    ui: ["Animal page (Identifiers card)"],
    body: "IdentifierCreate",
    responses: [{ status: 201, schema: "IdentifierOut" }],
    rules: ["Writes an identifier_added audit event."],
    errors: [{ status: 409, when: "The value is already attached to an animal.", code: "identifier.duplicate" }],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/identifiers",
    service: "animal",
    summary: "List an animal's identifiers",
    priority: "required",
    ui: ["Animal page (Identifiers card)", "Print records"],
    fn: "listIdentifiers",
    responses: [{ status: 200, schema: "IdentifierOut", array: true }],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/offspring",
    service: "animal",
    summary: "Animals that have this one as sire or dam",
    priority: "required",
    ui: ["Animal page (Lineage card)"],
    fn: "listOffspring",
    responses: [{ status: 200, schema: "AnimalOut", array: true }],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/parent-candidates",
    service: "animal",
    summary: "Who can be this animal's sire and dam",
    priority: "recommended",
    ui: ["Record menu → Update lineage"],
    fn: "listParentCandidates",
    responses: [{ status: 200, schema: "ParentCandidates" }],
    rules: [
      "sires: animals with gender bull. dams: gender cow or heifer. Both across all of the customer's ranches.",
      "Leave out the animal itself and everything descended from it, so the form can't offer a choice PATCH would refuse.",
      "Fallback if not built: the UI can filter GET /animals by gender itself, but then only PATCH catches loops.",
    ],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/cost-estimates",
    service: "animal",
    summary: "Cost-estimate history",
    priority: "required",
    ui: ["Animal page (Cost estimate card, Estimated value)"],
    fn: "listCostEstimates",
    responses: [{ status: 200, schema: "CostEstimateOut", array: true }],
    rules: ["Newest estimated_at first. When two share a date, the one created last comes first. The first item is “the current estimate”."],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "POST",
    path: "/animals/{animal_id}/cost-estimates",
    service: "animal",
    summary: "Add a cost estimate",
    priority: "required",
    ui: ["Record menu → Cost estimate"],
    fn: "recordCostEstimate",
    body: "CostEstimateCreate",
    responses: [{ status: 201, schema: "CostEstimateOut" }],
    rules: ["Never overwrites: each estimate is a new row. Writes an estimate_recorded audit event."],
    errors: [ANIMAL_NOT_FOUND],
  },

  // ---- ranches & zones ----
  {
    method: "GET",
    path: "/ranches",
    service: "animal",
    summary: "List ranches",
    priority: "required",
    ui: ["Dashboard", "Ranches", "Pickers in forms"],
    fn: "listRanches",
    responses: [{ status: 200, schema: "RanchOut", array: true }],
    rules: ["Now includes boundary and the derived counts. breach_count needs gps-service, so a gateway (or a call into gps-service) fills it in."],
  },
  {
    method: "POST",
    path: "/ranches",
    service: "animal",
    summary: "Onboard a ranch",
    priority: "required",
    ui: ["New ranch"],
    body: "RanchCreate",
    responses: [{ status: 201, schema: "RanchOut" }],
    rules: ["Boundary is stored as geography(Polygon, 4326). Writes a ranch_created audit event."],
    errors: [{ status: 422, when: "The boundary isn't a valid closed polygon.", code: "geometry.invalid_polygon" }],
  },
  {
    method: "GET",
    path: "/ranches/{ranch_id}",
    service: "animal",
    summary: "Get a ranch",
    priority: "required",
    ui: ["Ranch page", "Animal page (Overview)", "Print records"],
    fn: "getRanch",
    responses: [{ status: 200, schema: "RanchOut" }],
    errors: [E404],
  },
  {
    method: "GET",
    path: "/ranches/{ranch_id}/audit-trail",
    service: "animal",
    summary: "Audit trail for a ranch",
    priority: "required",
    ui: ["Ranch page", "Activity feed"],
    fn: "getRanchAuditTrail",
    responses: [{ status: 200, schema: "AuditEventOut", array: true }],
    errors: [E404],
  },
  {
    method: "POST",
    path: "/ranches/{ranch_id}/zones",
    service: "animal",
    summary: "Create a zone",
    priority: "required",
    ui: ["New zone"],
    body: "ZoneCreate",
    responses: [{ status: 201, schema: "ZoneOut" }],
    rules: ["Writes a zone_created audit event."],
    errors: [E404],
  },
  {
    method: "GET",
    path: "/ranches/{ranch_id}/zones",
    service: "animal",
    summary: "List a ranch's zones",
    priority: "required",
    ui: ["Ranch page (map and zone list)"],
    fn: "listZones",
    params: [{ name: "zone_type", in: "query", type: "string", enum: ["pasture", "water", "dangerous_terrain", "forest", "paddock", "quarantine"] }],
    responses: [{ status: 200, schema: "ZoneOut", array: true }],
    errors: [E404],
  },
  {
    method: "GET",
    path: "/ranches/{ranch_id}/zones/{zone_id}",
    service: "animal",
    summary: "Get a zone",
    priority: "recommended",
    ui: [],
    responses: [{ status: 200, schema: "ZoneOut" }],
    errors: [E404],
  },
  {
    method: "PATCH",
    path: "/ranches/{ranch_id}/zones/{zone_id}",
    service: "animal",
    summary: "Rename, describe or lift a zone",
    priority: "required",
    ui: ["Ranch page (zone editor)"],
    body: "ZoneUpdate",
    responses: [{ status: 200, schema: "ZoneOut" }],
    rules: ["active: false lifts the zone (sets lifted_at). Writes a zone_updated audit event with { name, active }."],
    errors: [E404],
  },
  {
    method: "GET",
    path: "/healthz",
    service: "animal",
    summary: "Liveness check",
    priority: "recommended",
    ui: [],
    responses: [{ status: 200 }],
    rules: ["Not called by the frontend. Every service should expose the same."],
  },

  // ======================= health-service =======================
  {
    method: "GET",
    path: "/animals/{animal_id}/vaccinations",
    service: "health",
    summary: "An animal's vaccinations",
    priority: "required",
    ui: ["Animal page", "Print records"],
    fn: "listVaccinations",
    responses: [{ status: 200, schema: "VaccinationOut", array: true }],
    rules: ["Newest administered_at first. All doses, not just the latest per vaccine."],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "POST",
    path: "/animals/{animal_id}/vaccinations",
    service: "health",
    summary: "Record a vaccination",
    priority: "required",
    ui: ["Record menu → Vaccination"],
    fn: "recordVaccination",
    body: "VaccinationCreate",
    responses: [{ status: 201, schema: "VaccinationOut" }],
    rules: [
      "Writes a vaccination_recorded audit event with { vaccine, dose_ml, next_due_at }.",
      "Recording a dose moves that vaccine's next-due date forward for the animal, which clears its overdue/due-soon alerts.",
    ],
    errors: [ANIMAL_NOT_FOUND, { status: 422, when: "next_due_at is before administered_at.", code: "vaccination.due_before_given" }],
  },
  {
    method: "GET",
    path: "/vaccinations",
    service: "health",
    summary: "Latest dose of each vaccine per active animal, with due state",
    priority: "required",
    ui: ["Dashboard (Overdue vaccines)", "Vaccinations drill-down"],
    fn: "listVaccinationStatus",
    params: [ranchQ, { name: "state", in: "query", type: "string", enum: ["overdue", "due_soon", "ok"] }],
    responses: [{ status: 200, schema: "VaccinationRow", array: true }],
    rules: [
      "One row per (active animal, vaccine): the dose with the latest administered_at. Sold and deceased animals are excluded.",
      "state: overdue when next_due_at is in the past; due_soon when it is within the next 30 days; otherwise ok. days = whole days until due, rounded up.",
      "Most overdue first (ascending days).",
    ],
  },
  {
    method: "GET",
    path: "/vaccines",
    service: "health",
    summary: "Vaccine catalog with usual intervals",
    priority: "recommended",
    ui: ["Record menu → Vaccination (suggestions and next-due date)"],
    responses: [{ status: 200, schema: "VaccineOut", array: true }],
    rules: [
      "Hard-coded in the frontend today (src/lib/vaccines.ts): 7-way Clostridial 365, BVD/IBR/PI3/BRSV 365, Blackleg 180, Brucellosis (RB51) 3650, Leptospirosis 365 days.",
      "The form still accepts any vaccine name; this only powers suggestions.",
    ],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/observations",
    service: "health",
    summary: "An animal's health observations",
    priority: "required",
    ui: ["Animal page", "Print records"],
    fn: "listObservations",
    responses: [{ status: 200, schema: "ObservationOut", array: true }],
    rules: ["Newest observed_at first."],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "POST",
    path: "/animals/{animal_id}/observations",
    service: "health",
    summary: "Record a health observation",
    priority: "required",
    ui: ["Record menu → Health observation"],
    fn: "recordObservation",
    body: "ObservationCreate",
    responses: [{ status: 201, schema: "ObservationOut" }],
    rules: ["Writes a health_recorded audit event with { kind, severity, notes }.", "severity high on an active animal raises a critical alert for 21 days."],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/breeding",
    service: "health",
    summary: "An animal's breeding events",
    priority: "required",
    ui: ["Animal page (Breeding)", "Print records"],
    fn: "listBreeding",
    responses: [{ status: 200, schema: "BreedingEventOut", array: true }],
    rules: ["Newest first. The UI has no form to create these yet, so there is no POST here; add one when the screen exists."],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/weights",
    service: "health",
    summary: "An animal's weigh-ins",
    priority: "required",
    ui: ["Animal page (Weight history, Last weight)", "Print records"],
    fn: "listWeights",
    responses: [{ status: 200, schema: "WeightOut", array: true }],
    rules: ["Oldest first (it feeds a chart). Weights are pounds."],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "POST",
    path: "/animals/{animal_id}/weights",
    service: "health",
    summary: "Record a weigh-in",
    priority: "required",
    ui: ["Record menu → Weight check"],
    fn: "recordWeight",
    body: "WeightCreate",
    responses: [{ status: 201, schema: "WeightOut" }],
    rules: ["Writes a weight_recorded audit event with { weight_lb }. The plan allows this to live in animal-service instead."],
    errors: [ANIMAL_NOT_FOUND],
  },

  // ======================= gps-service =======================
  {
    method: "GET",
    path: "/animals/{animal_id}/position",
    service: "gps",
    summary: "Latest position of an animal",
    priority: "required",
    ui: ["Animal page (outside-boundary banner)"],
    fn: "getPosition",
    responses: [{ status: 200, schema: "PositionOut" }],
    rules: ["404 (or null) when there is no ping, or when the animal isn't active: sold and deceased animals never show a position."],
    errors: [{ status: 404, when: "No position, or the animal is not active." }],
  },
  {
    method: "GET",
    path: "/ranches/{ranch_id}/positions",
    service: "gps",
    summary: "Latest position of every active animal on a ranch",
    priority: "required",
    ui: ["Ranch page (live map)"],
    fn: "listRanchPositions",
    responses: [{ status: 200, schema: "PositionOut", array: true }],
    rules: ["One row per active animal (its latest ping). Excludes sold and deceased animals."],
    errors: [E404],
  },
  {
    method: "GET",
    path: "/breaches",
    service: "gps",
    summary: "Recent boundary breaches",
    priority: "required",
    ui: ["Dashboard (Boundary breaches)", "Breaches drill-down"],
    fn: "listBreaches",
    params: [ranchQ, { name: "since_days", in: "query", type: "integer", description: "Look-back window. Default 7." }],
    responses: [{ status: 200, schema: "BreachOut", array: true }],
    rules: [
      "Backed by geofence_breach audit events. Newest first.",
      "Only active animals: a breach by an animal that has since been sold is not returned.",
      "distance_m is measured to the nearest point on the ranch boundary.",
    ],
  },

  // ======================= compliance-service =======================
  {
    method: "GET",
    path: "/movements",
    service: "compliance",
    summary: "List movements",
    priority: "required",
    ui: ["Compliance", "Dashboard"],
    fn: "listMovements",
    params: [ranchQ, { name: "status", in: "query", type: "string", enum: ["completed", "pending", "flagged"] }],
    responses: [{ status: 200, schema: "MovementOut", array: true }],
    rules: [
      "Newest moved_at first.",
      "issues is computed: “No CVI attached to an interstate movement” when kind is interstate and no attached document has doc_type cvi; and “<CVI title> expires before the movement date” for each attached CVI whose expires_at is before moved_at.",
      "The UI treats a movement with any issues as flagged and raises a critical movement_issue alert.",
    ],
  },
  {
    method: "POST",
    path: "/movements",
    service: "compliance",
    summary: "Record a movement",
    priority: "required",
    ui: ["New movement"],
    body: "MovementCreate",
    responses: [{ status: 201, schema: "MovementOut" }],
    rules: ["Writes one movement_recorded audit event per animal, with { direction, purpose, kind, place, movement_id, cvi }."],
    errors: [{ status: 422, when: "An animal id doesn't exist or isn't on the ranch.", code: "movement.unknown_animal" }],
  },
  {
    method: "GET",
    path: "/movements/{movement_id}",
    service: "compliance",
    summary: "Get a movement",
    priority: "required",
    ui: ["Movement page"],
    fn: "getMovement",
    responses: [{ status: 200, schema: "MovementOut" }],
    errors: [E404],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/movements",
    service: "compliance",
    summary: "Movements an animal was part of",
    priority: "required",
    ui: ["Animal page (Compliance card)", "Print records"],
    fn: "listAnimalMovements",
    responses: [{ status: 200, schema: "MovementOut", array: true }],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "GET",
    path: "/documents",
    service: "compliance",
    summary: "List documents",
    priority: "required",
    ui: ["Compliance"],
    fn: "listDocuments",
    params: [ranchQ, { name: "doc_type", in: "query", type: "string", enum: ["cvi", "brand_inspection", "test_results", "registry_papers", "health_certificate"] }],
    responses: [{ status: 200, schema: "DocumentOut", array: true }],
    rules: [
      "Newest issued_at first.",
      "status and days_left are computed from expires_at and today: no expires_at → valid, days_left null. Otherwise days_left = whole days to expiry (rounded up, negative when past).",
      "archived: the document has an expires_at and is attached to a movement whose status is completed (its expiry no longer matters). Documents with no expires_at are always valid.",
      "Otherwise: expired when days_left < 0; expiring when 0 ≤ days_left ≤ 30; valid beyond that.",
    ],
  },
  {
    method: "POST",
    path: "/documents",
    service: "compliance",
    summary: "Register a document",
    priority: "required",
    ui: ["New document"],
    body: "DocumentCreate",
    responses: [{ status: 201, schema: "DocumentCreated" }],
    rules: [
      "Writes a document_uploaded audit event with { title, doc_type, document_id }.",
      "The UI only sends metadata today. With storage connected, return a presigned S3 upload_url and let the UI PUT the file to it (a small frontend change).",
      "expires_at is required for doc_type cvi, test_results and health_certificate.",
    ],
    errors: [{ status: 422, when: "expires_at missing for a type that needs one, or not after issued_at.", code: "document.bad_expiry" }],
  },
  {
    method: "GET",
    path: "/documents/{document_id}",
    service: "compliance",
    summary: "Get a document",
    priority: "required",
    ui: ["Document page"],
    fn: "getDocument",
    responses: [{ status: 200, schema: "DocumentOut" }],
    errors: [E404],
  },
  {
    method: "GET",
    path: "/animals/{animal_id}/documents",
    service: "compliance",
    summary: "Documents that cover an animal",
    priority: "required",
    ui: ["Animal page (Compliance card)", "Print records (download widget)"],
    fn: "listAnimalDocuments",
    responses: [{ status: 200, schema: "DocumentOut", array: true }],
    errors: [ANIMAL_NOT_FOUND],
  },
  {
    method: "GET",
    path: "/documents/{document_id}/download",
    service: "compliance",
    summary: "Download the original file",
    priority: "required",
    ui: ["Document page", "Print records (download widget)"],
    responses: [{ status: 302, description: "Redirect to a short-lived signed S3 URL, with Content-Disposition: attachment." }],
    rules: [
      "The browser follows this URL directly, so it must work with plain cookie or token auth and no custom headers.",
      "Today the frontend serves a generated placeholder PDF at /api/documents/{id}/download. Keep that URL as a thin proxy that redirects here, so no screen changes.",
    ],
    errors: [E404],
  },
  {
    method: "GET",
    path: "/compliance/summary",
    service: "compliance",
    summary: "Counters for the Compliance page",
    priority: "recommended",
    ui: ["Compliance"],
    fn: "getComplianceSummary",
    responses: [{ status: 200, schema: "ComplianceSummary" }],
    rules: ["The frontend could count from the two lists; this saves fetching everything."],
  },

  // ======================= platform / gateway =======================
  {
    method: "GET",
    path: "/alerts",
    service: "platform",
    summary: "Current alerts",
    priority: "required",
    ui: ["Alerts bell and /alerts", "Dashboard", "Banner"],
    fn: "listAlerts",
    params: [ranchQ],
    responses: [{ status: 200, schema: "AlertOut", array: true }],
    rules: [
      "Ordered most severe first (critical, warning, info); within critical and warning, newest first; within info, soonest first.",
      "geofence_breach (critical): a geofence_breach event in the last 7 days for an active animal. id = the audit event id.",
      "health (critical): observation with severity high in the last 21 days, active animal. title “High-severity health note”, detail = the notes.",
      "movement_issue (critical): any movement with issues. subject “Origin → Destination” (place names before the comma); detail = the first issue.",
      "vaccination_overdue (warning): latest dose per (active animal, vaccine) past due. title “<vaccine> overdue”, detail “Was due <Mon D>”.",
      "document_expired (warning) / document_expiring (info): document status expired / expiring. title “Document expired” / “Document expiring”.",
      "vaccination_due (info): due within 30 days. title “<vaccine> due soon”, detail “Due <Mon D>”.",
      "Sold and deceased animals raise no alerts.",
      "Read-state (which alerts a person has seen) is kept in the browser today. Per-user acknowledgement would need its own endpoint later.",
    ],
  },
  {
    method: "GET",
    path: "/dashboard",
    service: "platform",
    summary: "Everything on the dashboard",
    priority: "recommended",
    ui: ["Dashboard"],
    fn: "getDashboard",
    responses: [{ status: 200, schema: "DashboardOut" }],
    rules: ["A gateway/BFF endpoint composing the services. Without it, the UI would need about seven calls to draw the first screen."],
  },
  {
    method: "GET",
    path: "/audit-events",
    service: "platform",
    summary: "Activity feed across ranches",
    priority: "required",
    ui: ["Activity feed"],
    fn: "listAllAuditEvents",
    params: [
      ranchQ,
      { name: "animal_id", in: "query", type: "string" },
      { name: "event_type", in: "query", type: "string" },
      { name: "limit", in: "query", type: "integer", description: "The UI shows the newest ~200 today." },
      { name: "before", in: "query", type: "string", description: "Cursor: return events older than this occurred_at." },
    ],
    responses: [{ status: 200, schema: "AuditEventOut", array: true }],
    rules: ["The shared audit table across all services, newest first."],
  },
  {
    method: "GET",
    path: "/me",
    service: "platform",
    summary: "The signed-in user",
    priority: "recommended",
    ui: ["App shell"],
    responses: [{ status: 200, schema: "MeOut" }],
    rules: ["The customer name in the shell (“Bartlett Cattle Co.”) and the actor names are placeholders today."],
    errors: [{ status: 401, when: "Missing or invalid JWT." }],
  },
];
